### ISSUE TITLE
UI(ADMIN) - Create a login register page in admin

### ISSUE THREAD

**Issue by Kuroidaka** [idaka123/GameStore-Admin#1]
> [SCRIPT](https://github.com/idaka123/GameStore/wiki/UI(Admin)-Authentication-Page)

base on this link: https://dribbble.com/shots/19338138-Log-in-page-Untitled-UI

Create a new authenticate page (login, register)

**Comment by Kuroidaka** [comment]
@Kouzira announce me when you in process this task

**Comment by Kuroidaka** [comment]
Hi Team 
I have update the UI and several logic for Auth page

**we do not need to use firebase in admin page, it is can be use in source landing page that we are going to set it up later**

![image](https://user-images.githubusercontent.com/75541791/233856142-82229517-0f3b-4cf2-a0d6-846b933ecf50.png)
![image](https://user-images.githubusercontent.com/75541791/233856153-eb960da1-7691-4143-83c8-1a1961dc76ff.png)

Thanks

**Comment by Kuroidaka** [comment]
@Kouzira 

I added the code template for show error in input field for validation

task: 
- add validation for input password confirm with password

**using this code template which have been set up in InputField component**
![Image](https://user-images.githubusercontent.com/75541791/233892663-0464301b-07f0-4fb0-aceb-2bef5cacbf2a.png)

if set errorState = {true}

the UI will show like this 


![Image](https://user-images.githubusercontent.com/75541791/233893086-2b73b772-ec8a-4e60-8c4a-cc63a7842b64.png)

**Comment by Kuroidaka** [comment]
Hi @Kouzira 

I have clean the code and update some feature for validation base on your code 
What: 
- show error when submit while input fields empty 
- hide error when user input in specific input field
- show error when confirm password do not match password
- show alert when value do not match the email form in email input field 

<img width="355" alt="image" src="https://user-images.githubusercontent.com/75541791/235056133-18804512-6f16-488a-b8eb-c857f6b367f4.png">
<img width="455" alt="image" src="https://user-images.githubusercontent.com/75541791/235056160-364698e7-b172-4554-b956-ebfa7c12fe7b.png">
<img width="413" alt="image" src="https://user-images.githubusercontent.com/75541791/235056389-2e52f6cb-fb80-4ae1-88ec-9fa9cc34d765.png">
<img width="432" alt="image" src="https://user-images.githubusercontent.com/75541791/235056414-32d00875-0961-4428-b328-1ac698d53005.png">
<img width="534" alt="image" src="https://user-images.githubusercontent.com/75541791/235056499-f214844d-50f4-4690-bb71-baedb285a0ff.png">

**Comment by FOX2920** [comment]
@idaka123 I have just finished coding the header section (which now includes a search box and user avatar).
This is what it looks like:
![Screenshot_99](https://user-images.githubusercontent.com/91709267/236505084-75afb5df-8844-4e40-ae86-236ac304bb32.png)
Please let me know if there are any errors.
Thank you.
