### ISSUE TITLE
UI(ADMIN) - Create game management page

### ISSUE THREAD

**Issue by Kuroidaka** [idaka123/GameStore-Admin#5]
> [SCRIPT](https://github.com/idaka123/GameStore/wiki/UI(ADMIN)-Game-management-page)

Task:  
base on this [link](https://dribbble.com/shots/14333883-PionerLabs-Product-Information-Management-Tool-Interactions)

Update the UI for the game management page 

Step 1 : update the header section

![Image](https://user-images.githubusercontent.com/75541791/236642188-17c31e0b-baef-41d9-acda-d72aec90e166.png)

step 2 : update the search bar 

![Image](https://user-images.githubusercontent.com/75541791/236642222-67bad736-fc85-464a-8252-7d6ff9073a57.png)

step 3 update the game list 
we will use the layout on this [link](https://dribbble.com/shots/20295569-Kittodesign-Marketplace-Affiliate-Page) for the game list

![Image](https://user-images.githubusercontent.com/75541791/236642699-32d51917-7340-4c3c-b792-936bb4783bee.png)

URL: http://localhost:3000/game-manage
Source: 

![Image](https://user-images.githubusercontent.com/75541791/236642882-69676ac5-a271-42e2-8e2a-944c3b4ad170.png)

**Comment by FOX2920** [comment]
@idaka123 The UI code is done, but some parts of the web are still incomplete(I thịnk)
![Screenshot_106](https://user-images.githubusercontent.com/91709267/236684589-37ef97ef-65e0-40e2-ac42-f2870d7fed15.png)

**Comment by Kuroidaka** [comment]
https://github.com/idaka123/GameStore/wiki/UI(ADMIN)-Game-management-page#task-2-update-the-game-list 
Please base on this docs, enhance our UI for game management page
